<?php

namespace Database\Seeders;

use App\Models\Lesson;
use Illuminate\Database\Seeder;

class RichLessonsSeeder extends Seeder
{
    public function run(): void
    {
        $lessons = [
            'phonetics-first-sounds' => [
                'summary' => 'Фонетика помогает читать слова точнее: в английском буквы и звуки часто не совпадают.',
                'content' => '<h2>Буква и звук</h2><p>В английском языке одна и та же буква может читаться по-разному: a в словах cat [kæt], name [neɪm], father [ˈfɑːðə]. Поэтому важно смотреть не только на написание, но и на транскрипцию.</p><h2>Базовые звуки</h2><table><tr><th>Звук</th><th>Примеры</th><th>Что важно</th></tr><tr><td>[æ]</td><td>cat, apple, bad</td><td>Короткий открытый звук между русскими “э” и “а”.</td></tr><tr><td>[ɪ]</td><td>sit, big, fish</td><td>Короткий звук; не тянуть как русское “ии”.</td></tr><tr><td>[iː]</td><td>see, tea, green</td><td>Длинный звук; в транскрипции двоеточие показывает долготу.</td></tr><tr><td>[ʊ]</td><td>book, good, look</td><td>Короткий звук, ближе к краткому “у”.</td></tr><tr><td>[θ]</td><td>think, three, thanks</td><td>Язык между зубами; это не [s] и не [t].</td></tr><tr><td>[ð]</td><td>this, mother, they</td><td>Похожее положение языка, но звук звонкий.</td></tr></table><h2>Как читать транскрипцию</h2><ul><li>Квадратные скобки показывают звучание: word [wɜːd].</li><li>Знак ˈ показывает ударение: student [ˈstjuːdənt].</li><li>Двоеточие после символа означает долгий звук: [iː], [uː], [ɑː].</li></ul><h2>Минимальные пары</h2><table><tr><th>Пара</th><th>Разница</th><th>Перевод</th></tr><tr><td>ship / sheep</td><td>[ɪ] и [iː]</td><td>корабль / овца</td></tr><tr><td>full / fool</td><td>[ʊ] и [uː]</td><td>полный / дурак</td></tr><tr><td>bad / bed</td><td>[æ] и [e]</td><td>плохой / кровать</td></tr></table><h2>Частые ошибки</h2><ul><li>Читать английские слова русскими буквами: “зис” вместо this [ðɪs].</li><li>Не различать короткие и длинные гласные: ship и sheep звучат по-разному.</li><li>Игнорировать ударение: в английском оно может сильно менять естественность речи.</li></ul><div class="note">Практика: выберите 5 слов из словаря, выпишите транскрипцию, отметьте ударение и произнесите каждое слово медленно 3 раза.</div>',
            ],
            'present-simple' => [
                'summary' => 'Present Simple описывает привычки, факты, расписания и регулярные действия.',
                'content' => '<h2>Когда использовать</h2><ul><li>Привычки и режим: I drink tea every morning.</li><li>Постоянные факты: Water boils at 100 degrees.</li><li>Расписание: The train leaves at seven.</li><li>Состояния и мнения: I like music. She knows the answer.</li></ul><h2>Формы</h2><table><tr><th>Кто</th><th>Утверждение</th><th>Отрицание</th><th>Вопрос</th></tr><tr><td>I / you / we / they</td><td>I work.</td><td>I do not work.</td><td>Do you work?</td></tr><tr><td>he / she / it</td><td>She works.</td><td>She does not work.</td><td>Does she work?</td></tr></table><h2>Окончание -s у he/she/it</h2><table><tr><th>Правило</th><th>Пример</th></tr><tr><td>Обычно добавляем -s</td><td>read - reads, play - plays</td></tr><tr><td>После -s, -sh, -ch, -x, -o добавляем -es</td><td>watch - watches, go - goes</td></tr><tr><td>Согласная + y: y меняется на -ies</td><td>study - studies, try - tries</td></tr><tr><td>Гласная + y: просто -s</td><td>play - plays, enjoy - enjoys</td></tr></table><div class="note">В вопросе и отрицании окончание -s переходит в does: Does she study? She does not study. Не пишем Does she studies?</div><h2>Маркеры времени</h2><p>always, usually, often, sometimes, never, every day, every week, on Mondays, in the morning.</p><h2>Примеры</h2><table><tr><th>Английский</th><th>Русский</th><th>Комментарий</th></tr><tr><td>We learn English at school.</td><td>Мы учим английский в школе.</td><td>Регулярное действие.</td></tr><tr><td>He never eats fish.</td><td>Он никогда не ест рыбу.</td><td>He + eats.</td></tr><tr><td>Does your sister work?</td><td>Твоя сестра работает?</td><td>Вопрос через does.</td></tr></table><h2>Частые ошибки</h2><ul><li>Забывать -s: She work вместо She works.</li><li>Ставить -s дважды: Does she works вместо Does she work.</li><li>Использовать Present Simple для действия прямо сейчас: I read now лучше заменить на I am reading now.</li></ul><h2>Мини-практика</h2><p>Напишите 4 предложения о себе: что вы обычно делаете, чего никогда не делаете, что делает ваш друг и один вопрос с Do/Does.</p>',
            ],
            'word-order' => [
                'summary' => 'Порядок слов помогает строить понятные английские предложения без дословного перевода с русского.',
                'content' => '<h2>Главная схема</h2><p>В обычном утверждении английский порядок довольно строгий: подлежащее + сказуемое + дополнение + место + время.</p><table><tr><th>Кто?</th><th>Что делает?</th><th>Что?</th><th>Где?</th><th>Когда?</th></tr><tr><td>I</td><td>read</td><td>a book</td><td>at home</td><td>in the evening</td></tr><tr><td>She</td><td>drinks</td><td>coffee</td><td>at work</td><td>every morning</td></tr><tr><td>We</td><td>meet</td><td>our friends</td><td>in the park</td><td>on Sundays</td></tr></table><h2>Почему нельзя переводить слово в слово</h2><p>В русском можно сказать “Кофе я люблю”, и смысл останется понятным. В английском порядок несёт грамматическую нагрузку: I like coffee правильно, а Coffee like I звучит как ошибка.</p><h2>Вопросы</h2><table><tr><th>Тип</th><th>Схема</th><th>Пример</th></tr><tr><td>Yes/No question</td><td>Do/Does + кто + глагол?</td><td>Do you like coffee?</td></tr><tr><td>Wh-question</td><td>Вопросительное слово + do/does + кто + глагол?</td><td>Where do you live?</td></tr><tr><td>To be</td><td>Am/Is/Are + кто?</td><td>Are you ready?</td></tr></table><h2>Место наречий</h2><ul><li>Наречия частоты обычно идут перед смысловым глаголом: I often read.</li><li>С глаголом to be они обычно идут после него: She is always polite.</li><li>Время чаще ставится в конец или начало: I study English every day. Every day I study English.</li></ul><h2>Частые ошибки</h2><ul><li>Ставить глагол в конец: I English learn вместо I learn English.</li><li>Забывать вспомогательное слово в вопросе: Where you live? вместо Where do you live?</li><li>Ставить время между глаголом и объектом без причины: I read every day books вместо I read books every day.</li></ul><div class="note">Проверка: найдите в предложении “кто?” и “что делает?”. Если они стоят не рядом, предложение стоит пересобрать.</div>',
            ],
            'articles-a-an-the' => [
                'summary' => 'Артикли показывают, говорим ли мы о новом/любом предмете или о конкретном и уже понятном.',
                'content' => '<h2>Идея артиклей</h2><p>В русском артиклей нет, поэтому важно думать не о переводе, а о ситуации: предмет один или несколько, новый или уже известный, конкретный или любой.</p><h2>A / an</h2><p>A и an используются только с исчисляемыми существительными в единственном числе, когда предмет один и ещё не конкретизирован.</p><table><tr><th>Артикль</th><th>Когда</th><th>Пример</th></tr><tr><td>a</td><td>Перед согласным звуком</td><td>a book, a student, a university</td></tr><tr><td>an</td><td>Перед гласным звуком</td><td>an apple, an hour, an engineer</td></tr></table><h2>The</h2><p>The нужен, когда собеседнику понятно, о каком именно предмете речь: предмет уже упоминали, он единственный в ситуации или уточнён контекстом.</p><table><tr><th>Ситуация</th><th>Пример</th><th>Комментарий</th></tr><tr><td>Первое и второе упоминание</td><td>I saw a dog. The dog was small.</td><td>Сначала новый предмет, потом уже известный.</td></tr><tr><td>Единственный объект</td><td>The sun is bright.</td><td>Солнце одно в нашем обычном контексте.</td></tr><tr><td>Уточнение</td><td>The book on the table is mine.</td><td>Не любая книга, а конкретная.</td></tr></table><h2>Когда артикля нет</h2><ul><li>Множественное число в общем смысле: Dogs are friendly.</li><li>Неисчисляемые существительные в общем смысле: Water is important.</li><li>Имена людей, большинство городов и стран: Anna, London, France.</li><li>Названия приёмов пищи в общем смысле: I have breakfast at eight.</li></ul><h2>Исключения и ловушки</h2><ul><li>Выбираем a/an по звуку, а не по букве: an hour, a university.</li><li>Нельзя сказать a water, если речь о воде как веществе. Можно a glass of water.</li><li>Профессии обычно требуют a/an: She is a doctor.</li></ul><div class="note">Быстрый тест: если можно поставить “один какой-то”, чаще нужен a/an. Если можно поставить “тот самый”, чаще нужен the.</div>',
            ],
            'simple-dialogues' => [
                'summary' => 'Мини-диалоги дают готовые фразы для знакомства, просьбы, уточнения и вежливого ответа.',
                'content' => '<h2>Знакомство</h2><table><tr><th>Фраза</th><th>Перевод</th><th>Когда использовать</th></tr><tr><td>Hello. My name is Alex.</td><td>Здравствуйте. Меня зовут Алекс.</td><td>Начало общения.</td></tr><tr><td>Nice to meet you.</td><td>Приятно познакомиться.</td><td>После представления.</td></tr><tr><td>Where are you from?</td><td>Откуда вы?</td><td>Нейтральный вопрос.</td></tr><tr><td>I am from Russia.</td><td>Я из России.</td><td>Ответ о стране.</td></tr></table><h2>Короткие ответы</h2><p>В английском часто отвечают не одним словом, а короткой фразой: Yes, I do. No, I do not. Yes, I am. No, I am not.</p><table><tr><th>Вопрос</th><th>Короткий ответ</th><th>Полный ответ</th></tr><tr><td>Do you speak English?</td><td>Yes, I do.</td><td>Yes, I speak English.</td></tr><tr><td>Are you a student?</td><td>No, I am not.</td><td>No, I am not a student.</td></tr><tr><td>Can you help me?</td><td>Yes, I can.</td><td>Yes, I can help you.</td></tr></table><h2>Просьбы и уточнения</h2><ul><li>Could you repeat, please? - Повторите, пожалуйста.</li><li>Can you speak slowly, please? - Говорите медленнее, пожалуйста.</li><li>What does this word mean? - Что значит это слово?</li><li>How do you spell it? - Как это пишется по буквам?</li></ul><h2>Пример диалога</h2><p>A: Hi, I am Kate. What is your name?<br>B: My name is Ivan. Nice to meet you.<br>A: Nice to meet you too. Do you study English?<br>B: Yes, I do. I study English for travel.</p><h2>Частые ошибки</h2><ul><li>Отвечать только Yes/No, когда лучше дать короткую грамматическую форму.</li><li>Путать How are you? и Who are you? Первое - “Как дела?”, второе - “Кто вы?”.</li><li>Забывать please в просьбах: с ним фраза звучит вежливее.</li></ul>',
            ],
            'to-be' => [
                'summary' => 'To be помогает говорить, кто или что кем является, где находится и в каком состоянии находится.',
                'content' => '<h2>Что значит to be</h2><p>To be переводится как “быть”, но в русском настоящем времени часто пропускается: I am a student - Я студент. В английском am/is/are обычно обязательны.</p><h2>Формы</h2><table><tr><th>Местоимение</th><th>Форма</th><th>Пример</th></tr><tr><td>I</td><td>am</td><td>I am ready.</td></tr><tr><td>he / she / it</td><td>is</td><td>She is tired. It is cold.</td></tr><tr><td>you / we / they</td><td>are</td><td>They are at home.</td></tr></table><h2>Утверждение, отрицание, вопрос</h2><table><tr><th>Тип</th><th>Схема</th><th>Пример</th></tr><tr><td>Утверждение</td><td>Кто + am/is/are</td><td>He is a teacher.</td></tr><tr><td>Отрицание</td><td>Кто + am/is/are + not</td><td>We are not late.</td></tr><tr><td>Вопрос</td><td>Am/Is/Are + кто?</td><td>Are you ready?</td></tr></table><h2>Когда использовать</h2><ul><li>Профессия или роль: She is a doctor.</li><li>Состояние: I am tired.</li><li>Место: They are in the room.</li><li>Возраст: He is ten years old.</li><li>Погода: It is warm today.</li></ul><h2>Сокращения</h2><table><tr><th>Полная форма</th><th>Сокращение</th></tr><tr><td>I am</td><td>I\'m</td></tr><tr><td>he is / she is / it is</td><td>he\'s / she\'s / it\'s</td></tr><tr><td>we are / they are / you are</td><td>we\'re / they\'re / you\'re</td></tr><tr><td>is not / are not</td><td>isn\'t / aren\'t</td></tr></table><h2>Частые ошибки</h2><ul><li>Пропускать глагол: I student вместо I am a student.</li><li>Смешивать do и to be: Do you are ready? вместо Are you ready?</li><li>Использовать is с множественным числом: They is вместо They are.</li></ul>',
            ],
            'pronouns' => [
                'summary' => 'Местоимения заменяют существительные и помогают не повторять одни и те же слова.',
                'content' => '<h2>Личные местоимения</h2><table><tr><th>Кто?</th><th>Перевод</th><th>Пример</th></tr><tr><td>I</td><td>я</td><td>I live here.</td></tr><tr><td>you</td><td>ты / вы</td><td>You are right.</td></tr><tr><td>he</td><td>он</td><td>He works.</td></tr><tr><td>she</td><td>она</td><td>She studies.</td></tr><tr><td>it</td><td>оно / это</td><td>It is cold.</td></tr><tr><td>we</td><td>мы</td><td>We are friends.</td></tr><tr><td>they</td><td>они</td><td>They speak English.</td></tr></table><h2>Объектные формы</h2><p>Если местоимение получает действие, нужна объектная форма: me, you, him, her, it, us, them.</p><table><tr><th>Кто?</th><th>Кого? кому?</th><th>Пример</th></tr><tr><td>I</td><td>me</td><td>She helps me.</td></tr><tr><td>he</td><td>him</td><td>I know him.</td></tr><tr><td>she</td><td>her</td><td>We see her.</td></tr><tr><td>we</td><td>us</td><td>They call us.</td></tr><tr><td>they</td><td>them</td><td>I like them.</td></tr></table><h2>Притяжательные формы</h2><table><tr><th>Форма</th><th>Перевод</th><th>Пример</th></tr><tr><td>my</td><td>мой</td><td>my book</td></tr><tr><td>your</td><td>твой / ваш</td><td>your name</td></tr><tr><td>his</td><td>его</td><td>his car</td></tr><tr><td>her</td><td>её</td><td>her bag</td></tr><tr><td>our</td><td>наш</td><td>our house</td></tr><tr><td>their</td><td>их</td><td>their room</td></tr></table><h2>Частые ошибки</h2><ul><li>Путать he и she: he - мужчина/мальчик, she - женщина/девочка.</li><li>Ставить объектную форму как подлежащее: Me like coffee вместо I like coffee.</li><li>Путать her: это может быть “её” и “ей/её” по контексту.</li></ul><div class="note">Проверка: если местоимение стоит перед глаголом и выполняет действие, обычно нужна форма I/he/she/we/they. Если действие направлено на него, нужна me/him/her/us/them.</div>',
            ],
            'plural-nouns' => [
                'summary' => 'Множественное число показывает, что предметов больше одного: book - books, child - children.',
                'content' => '<h2>Основное правило</h2><p>Обычно к существительному добавляется -s: one book - two books, one room - three rooms.</p><table><tr><th>Окончание слова</th><th>Что добавить</th><th>Пример</th></tr><tr><td>Обычный случай</td><td>-s</td><td>pen - pens</td></tr><tr><td>-s, -ss, -sh, -ch, -x</td><td>-es</td><td>box - boxes, class - classes</td></tr><tr><td>согласная + y</td><td>y меняется на -ies</td><td>city - cities, baby - babies</td></tr><tr><td>гласная + y</td><td>-s</td><td>toy - toys, day - days</td></tr><tr><td>часто -f / -fe</td><td>-ves</td><td>wife - wives, knife - knives</td></tr></table><h2>Неправильные формы</h2><table><tr><th>Ед. число</th><th>Мн. число</th><th>Перевод</th></tr><tr><td>child</td><td>children</td><td>дети</td></tr><tr><td>man</td><td>men</td><td>мужчины</td></tr><tr><td>woman</td><td>women</td><td>женщины</td></tr><tr><td>person</td><td>people</td><td>люди</td></tr><tr><td>mouse</td><td>mice</td><td>мыши</td></tr><tr><td>foot</td><td>feet</td><td>ступни</td></tr></table><h2>Слова без обычного множественного числа</h2><p>Некоторые слова неисчисляемые: water, money, information, advice. Обычно не говорим informations или advices. Нужно: some information, a piece of advice.</p><h2>Частые ошибки</h2><ul><li>Добавлять -s к неправильным формам: childs вместо children.</li><li>Использовать a/an с множественным числом: a books неверно.</li><li>Забывать менять глагол: The books are on the table, не The books is.</li></ul>',
            ],
            'questions-basic' => [
                'summary' => 'Базовые вопросы строятся через am/is/are, do/does, can или вопросительные слова.',
                'content' => '<h2>Два главных типа вопросов</h2><table><tr><th>Тип</th><th>Что спрашивает</th><th>Пример</th></tr><tr><td>Yes/No question</td><td>Ответ “да” или “нет”</td><td>Do you work?</td></tr><tr><td>Wh-question</td><td>Конкретная информация</td><td>Where do you work?</td></tr></table><h2>Вопросы с to be</h2><p>Если в утверждении есть am/is/are, в вопросе переносим этот глагол перед подлежащим.</p><table><tr><th>Утверждение</th><th>Вопрос</th><th>Короткий ответ</th></tr><tr><td>You are ready.</td><td>Are you ready?</td><td>Yes, I am.</td></tr><tr><td>She is tired.</td><td>Is she tired?</td><td>No, she isn\'t.</td></tr></table><h2>Вопросы с обычными глаголами</h2><p>В Present Simple нужны do/does. После does смысловой глагол идёт без -s.</p><table><tr><th>Кто</th><th>Вопрос</th><th>Правильно</th></tr><tr><td>I/you/we/they</td><td>Do you study?</td><td>Do they live here?</td></tr><tr><td>he/she/it</td><td>Does she study?</td><td>Does he live here?</td></tr></table><h2>Вопросительные слова</h2><table><tr><th>Слово</th><th>Значение</th><th>Пример</th></tr><tr><td>what</td><td>что / какой</td><td>What do you read?</td></tr><tr><td>where</td><td>где / куда</td><td>Where do you live?</td></tr><tr><td>when</td><td>когда</td><td>When do you work?</td></tr><tr><td>why</td><td>почему</td><td>Why do you learn English?</td></tr><tr><td>who</td><td>кто</td><td>Who is your teacher?</td></tr><tr><td>how</td><td>как</td><td>How are you?</td></tr></table><h2>Частые ошибки</h2><ul><li>Where you live? вместо Where do you live?</li><li>Does she works? вместо Does she work?</li><li>Do you are ready? вместо Are you ready?</li></ul><div class="note">Алгоритм: найдите главный глагол. Если это am/is/are или can, перенесите его вперёд. Если обычный глагол в Present Simple, добавьте do/does.</div>',
            ],
            'there-is' => [
                'summary' => 'There is / there are нужны, чтобы сказать, что что-то есть или находится где-то.',
                'content' => '<h2>Зачем нужна конструкция</h2><p>There is / there are не переводится дословно как “там есть” в каждом случае. Часто это просто “есть”, “находится”, “имеется”: There is a book on the table - На столе есть книга.</p><h2>Выбор формы</h2><table><tr><th>Форма</th><th>Когда</th><th>Пример</th></tr><tr><td>There is</td><td>Один предмет или неисчисляемое</td><td>There is a chair. There is water.</td></tr><tr><td>There are</td><td>Несколько предметов</td><td>There are two chairs.</td></tr></table><h2>Отрицания и вопросы</h2><table><tr><th>Тип</th><th>Пример</th><th>Перевод</th></tr><tr><td>Утверждение</td><td>There is a shop near here.</td><td>Здесь рядом есть магазин.</td></tr><tr><td>Отрицание</td><td>There is not a shop near here.</td><td>Здесь рядом нет магазина.</td></tr><tr><td>Вопрос</td><td>Is there a shop near here?</td><td>Здесь рядом есть магазин?</td></tr><tr><td>Множественное число</td><td>Are there any chairs?</td><td>Есть стулья?</td></tr></table><h2>Some и any</h2><ul><li>Some часто используется в утверждениях: There are some apples.</li><li>Any часто используется в вопросах и отрицаниях: Are there any apples? There are not any apples.</li></ul><h2>Частые ошибки</h2><ul><li>Использовать it is вместо there is: It is a book on the table неверно, если смысл “на столе есть книга”.</li><li>Говорить There is two chairs вместо There are two chairs.</li><li>Забывать артикль с исчисляемым существительным в единственном числе: There is book вместо There is a book.</li></ul>',
            ],
            'can-modal' => [
                'summary' => 'Can выражает умение, возможность, разрешение и вежливую просьбу.',
                'content' => '<h2>Главное правило</h2><p>После can глагол всегда идёт в базовой форме без to и без -s: I can swim. She can speak English. Нельзя: she cans, can to go.</p><table><tr><th>Тип</th><th>Схема</th><th>Пример</th></tr><tr><td>Утверждение</td><td>Кто + can + глагол</td><td>I can drive.</td></tr><tr><td>Отрицание</td><td>Кто + cannot/can\'t + глагол</td><td>He can\'t swim.</td></tr><tr><td>Вопрос</td><td>Can + кто + глагол?</td><td>Can you help me?</td></tr></table><h2>Значения can</h2><table><tr><th>Значение</th><th>Пример</th><th>Перевод</th></tr><tr><td>Умение</td><td>She can play the piano.</td><td>Она умеет играть на пианино.</td></tr><tr><td>Возможность</td><td>We can meet today.</td><td>Мы можем встретиться сегодня.</td></tr><tr><td>Просьба</td><td>Can you open the window?</td><td>Можешь открыть окно?</td></tr><tr><td>Разрешение</td><td>You can use my phone.</td><td>Ты можешь использовать мой телефон.</td></tr></table><h2>Can и could</h2><p>Could может быть прошедшей формой can или более вежливой просьбой: I could read when I was five. Could you repeat, please?</p><h2>Частые ошибки</h2><ul><li>Добавлять to: I can to help неверно.</li><li>Добавлять -s после he/she/it: She cans неверно.</li><li>Использовать do в вопросе: Do you can swim? вместо Can you swim?</li></ul>',
            ],
            'past-simple-start' => [
                'summary' => 'Past Simple описывает завершённые действия в прошлом: вчера, на прошлой неделе, в 2020 году.',
                'content' => '<h2>Когда использовать</h2><p>Past Simple нужен, когда действие закончилось в прошлом и часто есть понятный момент времени: yesterday, last week, two days ago, in 2020.</p><h2>Правильные глаголы</h2><table><tr><th>Правило</th><th>Пример</th></tr><tr><td>Обычно добавляем -ed</td><td>work - worked</td></tr><tr><td>Глагол уже заканчивается на -e: добавляем -d</td><td>live - lived</td></tr><tr><td>Согласная + y: y меняется на -ied</td><td>study - studied</td></tr><tr><td>Краткий ударный слог: удваиваем согласную</td><td>stop - stopped</td></tr></table><h2>Неправильные глаголы</h2><table><tr><th>Настоящее</th><th>Прошедшее</th><th>Пример</th></tr><tr><td>go</td><td>went</td><td>I went home.</td></tr><tr><td>have</td><td>had</td><td>She had a meeting.</td></tr><tr><td>do</td><td>did</td><td>We did homework.</td></tr><tr><td>see</td><td>saw</td><td>He saw his friend.</td></tr><tr><td>buy</td><td>bought</td><td>They bought tickets.</td></tr></table><h2>Отрицания и вопросы</h2><p>В вопросах и отрицаниях используем did, а основной глагол возвращается в базовую форму.</p><table><tr><th>Тип</th><th>Пример</th></tr><tr><td>Утверждение</td><td>She visited London.</td></tr><tr><td>Отрицание</td><td>She did not visit London.</td></tr><tr><td>Вопрос</td><td>Did she visit London?</td></tr></table><div class="note">Не говорим Did she visited? После did нужен visit.</div><h2>Частые ошибки</h2><ul><li>Использовать was/were со всеми глаголами: I was worked неверно.</li><li>Забывать неправильные формы: goed вместо went.</li><li>Оставлять -ed после did: Did you watched? вместо Did you watch?</li></ul>',
            ],
            'future-going-to' => [
                'summary' => 'Be going to используется для планов, намерений и прогнозов по очевидным признакам.',
                'content' => '<h2>Форма</h2><p>Конструкция состоит из am/is/are + going to + глагол: I am going to study. She is going to call. They are going to travel.</p><table><tr><th>Кто</th><th>Форма</th><th>Пример</th></tr><tr><td>I</td><td>am going to</td><td>I am going to learn English.</td></tr><tr><td>he/she/it</td><td>is going to</td><td>He is going to cook dinner.</td></tr><tr><td>you/we/they</td><td>are going to</td><td>We are going to watch a film.</td></tr></table><h2>Когда использовать</h2><table><tr><th>Ситуация</th><th>Пример</th><th>Почему going to</th></tr><tr><td>План</td><td>I am going to visit my friend.</td><td>Решение уже есть.</td></tr><tr><td>Намерение</td><td>She is going to start a course.</td><td>Есть цель.</td></tr><tr><td>Прогноз по признакам</td><td>Look at the clouds. It is going to rain.</td><td>Есть видимое основание.</td></tr></table><h2>Отрицания и вопросы</h2><table><tr><th>Тип</th><th>Пример</th></tr><tr><td>Отрицание</td><td>I am not going to buy it.</td></tr><tr><td>Вопрос</td><td>Are you going to study today?</td></tr><tr><td>Wh-вопрос</td><td>What are you going to do?</td></tr></table><h2>Going to и will</h2><p>Going to чаще показывает заранее обдуманный план или очевидный прогноз. Will часто используют для решения в момент речи: I will help you.</p><h2>Частые ошибки</h2><ul><li>Пропускать am/is/are: I going to learn неверно.</li><li>Добавлять лишнее to после основного глагола: going to to study неверно.</li><li>Путать going to как будущее и go to как движение: I am going to school - я иду в школу; I am going to study - я собираюсь учиться.</li></ul>',
            ],
            'reading-simple-text' => [
                'summary' => 'Простой текст легче понять, если сначала искать тему, знакомые слова и глаголы, а не переводить каждое слово.',
                'content' => '<h2>Стратегия чтения</h2><p>Цель первого чтения - понять общий смысл. Не нужно останавливаться на каждом незнакомом слове: часто значение можно догадаться по контексту.</p><h2>Порядок работы</h2><table><tr><th>Шаг</th><th>Что делать</th><th>Пример вопроса</th></tr><tr><td>1</td><td>Посмотрите на заголовок и знакомые слова</td><td>О чём текст?</td></tr><tr><td>2</td><td>Найдите главных людей/предметы</td><td>Кто действует?</td></tr><tr><td>3</td><td>Найдите глаголы</td><td>Что происходит?</td></tr><tr><td>4</td><td>Отметьте время и место</td><td>Где и когда?</td></tr><tr><td>5</td><td>Проверьте незнакомые слова</td><td>Какие слова важны для смысла?</td></tr></table><h2>Пример</h2><p>Anna lives in a small town. She works at a school. Every morning she drinks coffee and reads messages.</p><table><tr><th>Элемент</th><th>Ответ</th></tr><tr><td>Кто?</td><td>Anna</td></tr><tr><td>Что делает?</td><td>lives, works, drinks, reads</td></tr><tr><td>Где?</td><td>in a small town, at a school</td></tr><tr><td>Когда?</td><td>every morning</td></tr></table><h2>Как угадывать слова</h2><ul><li>Смотрите на часть речи: после a/an часто существительное.</li><li>Смотрите на соседние слова: drink coffee помогает понять drink.</li><li>Используйте общий смысл абзаца, а не одно слово отдельно.</li></ul><h2>Частые ошибки</h2><ul><li>Переводить каждое слово и терять общий смысл.</li><li>Игнорировать глаголы, хотя именно они держат действие.</li><li>Считать незнакомое слово главным, даже если без него смысл уже понятен.</li></ul><div class="note">Практика: прочитайте короткий абзац дважды. Первый раз - для общего смысла, второй - чтобы выписать 3 глагола и 3 существительных.</div>',
            ],
            'speaking-about-yourself' => [
                'summary' => 'Рассказ о себе строится из коротких блоков: имя, город, учёба/работа, интересы и цель изучения английского.',
                'content' => '<h2>Базовая структура</h2><table><tr><th>Блок</th><th>Шаблон</th><th>Пример</th></tr><tr><td>Имя</td><td>My name is...</td><td>My name is Anna.</td></tr><tr><td>Город</td><td>I live in...</td><td>I live in Kazan.</td></tr><tr><td>Учёба/работа</td><td>I am a...</td><td>I am a student.</td></tr><tr><td>Интересы</td><td>I like...</td><td>I like music and films.</td></tr><tr><td>Цель</td><td>I learn English for...</td><td>I learn English for travel.</td></tr></table><h2>Готовый пример</h2><p>My name is Anna. I live in Kazan. I am a student. I like music, films and walking with friends. I learn English for travel and work.</p><h2>Как расширить рассказ</h2><ul><li>Добавьте частотность: I usually read in the evening.</li><li>Добавьте причину: I learn English because I want to travel.</li><li>Добавьте деталь о семье или друзьях: I have a younger brother.</li><li>Добавьте просьбу к собеседнику: What about you?</li></ul><h2>Полезные фразы</h2><table><tr><th>Фраза</th><th>Перевод</th></tr><tr><td>I am interested in...</td><td>Я интересуюсь...</td></tr><tr><td>In my free time, I...</td><td>В свободное время я...</td></tr><tr><td>I want to improve my speaking.</td><td>Я хочу улучшить разговорную речь.</td></tr><tr><td>Could you repeat, please?</td><td>Повторите, пожалуйста.</td></tr></table><h2>Частые ошибки</h2><ul><li>Делать один длинный текст без пауз. Лучше 5-7 коротких предложений.</li><li>Пропускать am: I student вместо I am a student.</li><li>Говорить I like to music вместо I like music.</li><li>Бояться простых слов. Для A1 простота - это нормально.</li></ul><div class="note">Практика: запишите рассказ из 6 предложений и прочитайте вслух. Затем замените город, хобби и цель, чтобы получить новый вариант.</div>',
            ],
        ];

        foreach ($lessons as $slug => $data) {
            Lesson::where('slug', $slug)->update($data);
        }
    }
}
